### PR TITLE
Example files for meteo and meter devices

### PR DESCRIPTION
**Pull request by eheinrichmc**

### CODE REVIEW

**Comment by DerayGa** [comment]
+1 👍

**Comment by DerayGa** [comment]
small question, why send PR github not MR from gitlab ❓ 
document should build automatic when master branch is updated. then sync to github :octocat: 
@eheinrichmc

**Review by cyberworm — APPROVED** [review]
+1

**Comment by eheinrichmc** [comment]
good question. I don't really know, I think because nobody has done it 
yet :-)


Am 28.11.2017 um 02:56 schrieb Deray:

**Comment by lordmonkey42** [comment]
@eheinrichmc @DerayGa 

Every time we release a update for VCOM-API document, we only update the files in vcom-api/ folder, in other words, we only generate files in  vcom-api/ folder and push them to github.

And this time, the files has been modified are in other folder, so we have to make a request in here.

I think it is the reason.

**Comment by lordmonkey42** [comment]
+1

**Pull request merged**
